# dns-management-template.yml

parameters:
  - name: environment
    type: string
  - name: resourceGroup
    type: string
  - name: dnsZone
    type: string
  - name: scriptPath
    type: string
  - name: notifyUsers
    type: string

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # VM image to run the pipeline

stages:
  - stage: DNSManagement
    displayName: 'DNS Management'
    jobs:
      - job: ManageDNSRecords
        displayName: 'Manage DNS Records'
        steps:
          - task: Checkout@1
            displayName: 'Checkout code'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Your Azure Service Connection Name'  # Replace with your Azure DevOps service connection
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Setting up Azure authentication..."
                az account set --subscription $(subscriptionId)
            displayName: 'Authenticate to Azure'

          - script: |
              echo "Running DNS management script..."
              ENVIRONMENT=${{ parameters.environment }}
              RESOURCE_GROUP=${{ parameters.resourceGroup }}
              DNS_ZONE=${{ parameters.dnsZone }}
              SCRIPT_PATH=${{ parameters.scriptPath }}

              # Run the script with the appropriate parameters
              bash $SCRIPT_PATH -t CNAME -z $DNS_ZONE -n joke -a add -g $RESOURCE_GROUP -d joke2
            displayName: 'Execute DNS management script'

  - stage: ApprovalGate
    displayName: 'Approval Gate'
    condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'test'), eq(variables['Build.SourceBranchName'], 'prod')))
    jobs:
      - job: ManualApproval
        displayName: 'Approval for Test/Prod'
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: ${{ parameters.notifyUsers }}
              instructions: 'Please approve the changes to test or prod environments.'
              timeoutInMinutes: 60
