jobs:
  - job: ManageRecords
    displayName: "Manage DNS Records"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: AzureCLI@2
        displayName: "Login to Azure"
        inputs:
          azureSubscription: "$(azureServiceConnection)"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
            for record in $(echo "$(dnsRecords)" | jq -c '.[]'); do
              record_type=$(echo "$record" | jq -r '.type')
              record_name=$(echo "$record" | jq -r '.name')
              ttl=$(echo "$record" | jq -r '.ttl')
              value=$(echo "$record" | jq -r '.value')
              action=$(echo "$record" | jq -r '.action')

              if [ "$action" = "create" ]; then
                if [ "$record_type" = "A" ]; then
                  az network private-dns record-set a add-record \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --record-set-name "$record_name" \
                    --ipv4-address "$value" \
                    --ttl "$ttl"
                elif [ "$record_type" = "CNAME" ]; then
                  az network private-dns record-set cname set-record \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --record-set-name "$record_name" \
                    --cname "$value" \
                    --ttl "$ttl"
                else
                  echo "Unsupported DNS record type for create: $record_type"
                  exit 1
                fi
              elif [ "$action" = "update" ]; then
                if [ "$record_type" = "A" ]; then
                  az network private-dns record-set a update \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --name "$record_name" \
                    --set ttl=$ttl
                  az network private-dns record-set a remove-record \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --record-set-name "$record_name" \
                    --ipv4-address "$value"
                  az network private-dns record-set a add-record \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --record-set-name "$record_name" \
                    --ipv4-address "$value" \
                    --ttl "$ttl"
                elif [ "$record_type" = "CNAME" ]; then
                  az network private-dns record-set cname update \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --name "$record_name" \
                    --set cnameRecord.cname="$value" ttl=$ttl
                else
                  echo "Unsupported DNS record type for update: $record_type"
                  exit 1
                fi
              elif [ "$action" = "delete" ]; then
                if [ "$record_type" = "A" ]; then
                  az network private-dns record-set a remove-record \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --record-set-name "$record_name" \
                    --ipv4-address "$value"
                elif [ "$record_type" = "CNAME" ]; then
                  az network private-dns record-set cname remove-record \
                    --resource-group $(dnsZoneResourceGroup) \
                    --zone-name $(dnsZoneName) \
                    --record-set-name "$record_name" \
                    --cname "$value"
                else
                  echo "Unsupported DNS record type for delete: $record_type"
                  exit 1
                fi
              else
                echo "Unsupported action: $action"
                exit 1
              fi
            done
