parameters:
  - name: filePath
    type: string

jobs:
- job: ParseClusterInfo
  displayName: "Check if ClusterInfo.yaml Exists"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      if [ -f "${{ parameters.filePath }}" ]; then
        echo "##vso[task.setvariable variable=clusterInfoExists;isOutput=true]true"
      else
        echo "##vso[task.setvariable variable=clusterInfoExists;isOutput=true]false"
      fi
    displayName: "Check ClusterInfo.yaml"
