trigger: none

parameters:
  - name: serviceConnection
    displayName: "Service Connection"
    type: string

  - name: resourceGroup
    displayName: "Resource Group"
    type: string

  - name: clusterName
    displayName: "Cluster Name"
    type: string

  - name: folderPath
    displayName: "Folder Path"
    type: string

stages:
- stage: CI
  displayName: "Continuous Integration Checks"
  jobs:
  - template: templates/ci-template.yml

- stage: CheckClusterInfoExists
  displayName: "Check if ClusterInfo.yaml Exists"
  dependsOn: CI
  jobs:
  - template: templates/parse-clusterinfo.yml
    parameters:
      filePath: "$(folderPath)/clusterInfo.yaml"

- stage: Deploy
  displayName: "Deploy Infrastructure"
  dependsOn: CheckClusterInfoExists
  condition: eq(dependencies.CheckClusterInfoExists.outputs['ParseClusterInfo.clusterInfoExists'], 'true')
  jobs:
  - template: templates/deploy-iac.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      resourceGroup: ${{ parameters.resourceGroup }}
      bicepFile: "$(folderPath)/bicepparam.bicep"
      folderPath: "$(folderPath)"

- stage: CreateClusterInfo
  displayName: "Create ClusterInfo.yaml"
  dependsOn: CheckClusterInfoExists
  condition: eq(dependencies.CheckClusterInfoExists.outputs['ParseClusterInfo.clusterInfoExists'], 'false')
  jobs:
  - template: templates/generate-clusterinfo.yml
    parameters:
      clusterName: ${{ parameters.clusterName }}
      resourceGroup: ${{ parameters.resourceGroup }}
      filePath: "$(folderPath)/clusterInfo.yaml"
